networks:
  app-network:
    driver: bridge

services:
  # backend
  backend:
    build: ./backend
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
    env_file:
      - ./config/backend.env
  # frontend
  frontend:
    build: ./frontend
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    networks:
      - app-network
    env_file:
      - ./config/frontend.env

  # redis
  redis:
    image: redis:6.2.6-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - app-network

  # mysql
  mysql:
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      - ./config/etc.env
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d 
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  ai:
    build: ./AI
    ports:
      - ${AI_PORT}:${AI_PORT}
    networks:
      - app-network
    env_file:
      - ./config/AI.env

volumes:
  mysql-data:
  redis-data: